# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash
REPORT="load_report.json"
if [ ! -f "$REPORT" ]; then
  echo "Load report not found!"
  exit 1
fi

# Get average_load value from the JSON file
LOAD=$(jq .average_load $REPORT)

# Simple logic: scale app container count based on load
# (You can tweak these thresholds)
if [ "$LOAD" -lt 30 ]; then
  COUNT=1
elif [ "$LOAD" -lt 60 ]; then
  COUNT=2
else
  COUNT=3
fi

echo "Scaling app to $COUNT containers based on load $LOAD"

docker compose up -d --scale app=$COUNT
